version: '3.8'

services:
  backend:
    build:
      context: ./WEB_Backend_Trinkprotokolle
    container_name: backend
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./WEB_Frontend_Trinkprotokolle
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
