name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Check out code
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: List project files
        run: |
          ls -R

      # Build Docker images
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Test Frontend und Backend connection
      - name: Test Frontend and Backend Connectivity
        run: |
          sleep 10
          curl -I http://frontend:3000
          curl -I http://backend:3001

      # Run Backend tests
      - name: Run Backend Tests
        run: |
          docker-compose -f docker-compose.yml run backend npm ci
          docker-compose -f docker-compose.yml run backend npm test

      # Run Frontend tests
      - name: Run Frontend Tests
        run: |
          docker-compose -f docker-compose.yml run frontend npm ci
          docker-compose -f docker-compose.yml run frontend npx playwright install
          docker-compose -f docker-compose.yml run frontend npm test

    env:
      FRONTEND_URL: "http://frontend:3000"
      BACKEND_URL: "http://backend:3001"
      DB_HOST: "mongodb"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
