name: Playwright E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start frontend-Container
        run: docker compose up -d frontend 

      - name: Start mongodb-Container
        run: docker compose up -d mongodb

      - name: Start backend-Container
        run: docker compose up -d backend 

      - name: Run tests
        run: docker compose run --rm e2e-tests npm run test
        env:
          BASE_URL: http://frontend:3000

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Stop containers
        if: always()
        run: docker-compose down
